---
- hosts: all
  gather_facts: no
  tasks:
    - name: Create directory
      file:
        path: /home/ubuntu/ansible_test
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

