apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-site-deployment
  namespace: alexey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-site
  template:
    metadata:
      labels:
        app: react-site
    spec:
      containers:
        - name: react-site
          image: alexeymihaylovdev/demo:1.1
          ports:
            - containerPort: 80