apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-site-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: react-site.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-site-service
                port:
                  number: 80
                  
