apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-site-deployment
  namespace: alexey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-site
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: react-site
    spec:
      containers:
        - name: react-site
          image: alexeymihaylovdev/demo:2.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-hub-secret      
---
apiVersion: v1
kind: Service
metadata:
  name: react-site-service
  namespace: alexey
spec:
  selector:
    app: react-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

